# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '3690c49a-91cb-496a-8e43-5771a6eb5bcf'

  # Web app name
  webAppName: 'hadzung-udacity-azure-project2'

  # Agent pool name
  agentName: 'myAgent'

  # Environment name
  environmentName: 'hadzung-udacity-azure-project2'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.13.0
  pythonVersion: '3.13.0'
pool:
  name: myAgent

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      name: $(agentName)
    steps:
    - script: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt update
        sudo apt-get install zip
        sudo apt install python3.12-venv
        python3 -m venv ~/.myrepo
        source ~/.myrepo/bin/activate
        python3 -m pip install --upgrade pip
        pip install setup
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements.txt"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop
